name: Build and release LaTeX document
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: 20220629_MICResearchDay.tex
          latexmk_use_lualatex: true
  release:
    runs-on: ubuntu-latest
    steps: 
    - name: Upload PDF as artifact
        uses: actions/upload-artifact@v2
        with:
          name: 20220629_MICResearchDay.pdf
          path: 20220629_MICResearchDay.${{ github.sha }}.pdf
